'use client';

import Image from 'next/image';

import style from './Main.module.css';
import SearchBar from './TopSection/Search/searchBar.jsx';
import Carousel from './TopSection/Carousel/carousel.jsx';
import Body from './Body/Body.jsx';

export default function Main() {
    const images = ['/img/body/pic1.jpg', '/img/body/pic2.jpg', '/img/body/pic3.jpg', '/img/body/pic4.jpg'];

    const immediatelyJobs = [
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/thinhphat.png',
            position: 'Nhân viên CSKH / Tư Vấn Qua Điện Thoại',
            company: 'Công ty CP PT kinh doanh Thịnh Phát',
            salary: '6 - 30 triệu',
            location: 'TP.HCM',
            time: '1',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
        {
            logo: '/img/jobs/netsg.png',
            position: 'Nhân viên tư vấn tại cửa hàng',
            company: 'Công ty cổ phần Người Bạn Vàng',
            salary: '9 - 15 triệu',
            location: 'Bình Dương',
            time: '2',
            requiredCV: false,
        },
    ];

    const urgentJobs = [
        {
            logo: '/img/jobs/maison.png',
            position: 'Nhân viên bán hàng kiêm thu ngân',
            company: 'Công ty cổ phần Maison Retail Management',
            salary: '6 - 8 triệu',
            location: 'TP.HCM',
            time: '29',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/shopeefood.png',
            position: 'Tài xế Shopee Food',
            company: 'Công ty cổ phần Foody',
            salary: '10 - 17 triệu',
            location: 'TP.HCM',
            time: '9',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/vinschool.png',
            position: 'Chuyên viên giáo vụ',
            company: 'Công ty cổ phần Vinschool',
            salary: '10 - 15 triệu',
            location: 'TP.HCM',
            time: '26',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/maison.png',
            position: 'Nhân viên bán hàng kiêm thu ngân',
            company: 'Công ty cổ phần Maison Retail Management',
            salary: '6 - 8 triệu',
            location: 'TP.HCM',
            time: '29',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/shopeefood.png',
            position: 'Tài xế Shopee Food',
            company: 'Công ty cổ phần Foody',
            salary: '10 - 17 triệu',
            location: 'TP.HCM',
            time: '9',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/vinschool.png',
            position: 'Chuyên viên giáo vụ',
            company: 'Công ty cổ phần Vinschool',
            salary: '10 - 15 triệu',
            location: 'TP.HCM',
            time: '26',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/maison.png',
            position: 'Nhân viên bán hàng kiêm thu ngân',
            company: 'Công ty cổ phần Maison Retail Management',
            salary: '6 - 8 triệu',
            location: 'TP.HCM',
            time: '29',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/shopeefood.png',
            position: 'Tài xế Shopee Food',
            company: 'Công ty cổ phần Foody',
            salary: '10 - 17 triệu',
            location: 'TP.HCM',
            time: '9',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/vinschool.png',
            position: 'Chuyên viên giáo vụ',
            company: 'Công ty cổ phần Vinschool',
            salary: '10 - 15 triệu',
            location: 'TP.HCM',
            time: '26',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/maison.png',
            position: 'Nhân viên bán hàng kiêm thu ngân',
            company: 'Công ty cổ phần Maison Retail Management',
            salary: '6 - 8 triệu',
            location: 'TP.HCM',
            time: '29',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/shopeefood.png',
            position: 'Tài xế Shopee Food',
            company: 'Công ty cổ phần Foody',
            salary: '10 - 17 triệu',
            location: 'TP.HCM',
            time: '9',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/vinschool.png',
            position: 'Chuyên viên giáo vụ',
            company: 'Công ty cổ phần Vinschool',
            salary: '10 - 15 triệu',
            location: 'TP.HCM',
            time: '26',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/maison.png',
            position: 'Nhân viên bán hàng kiêm thu ngân',
            company: 'Công ty cổ phần Maison Retail Management',
            salary: '6 - 8 triệu',
            location: 'TP.HCM',
            time: '29',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/shopeefood.png',
            position: 'Tài xế Shopee Food',
            company: 'Công ty cổ phần Foody',
            salary: '10 - 17 triệu',
            location: 'TP.HCM',
            time: '9',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/vinschool.png',
            position: 'Chuyên viên giáo vụ',
            company: 'Công ty cổ phần Vinschool',
            salary: '10 - 15 triệu',
            location: 'TP.HCM',
            time: '26',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/maison.png',
            position: 'Nhân viên bán hàng kiêm thu ngân',
            company: 'Công ty cổ phần Maison Retail Management',
            salary: '6 - 8 triệu',
            location: 'TP.HCM',
            time: '29',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/shopeefood.png',
            position: 'Tài xế Shopee Food',
            company: 'Công ty cổ phần Foody',
            salary: '10 - 17 triệu',
            location: 'TP.HCM',
            time: '9',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/vinschool.png',
            position: 'Chuyên viên giáo vụ',
            company: 'Công ty cổ phần Vinschool',
            salary: '10 - 15 triệu',
            location: 'TP.HCM',
            time: '26',
            requiredCV: true,
        },
    ];

    const anotherJobs = [
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '31',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '78',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/ngocanh.png',
            position: 'Kế toán nội bộ',
            company: 'Công ty TNHH Ngọc Anh Sài Gòn',
            salary: '14 - 20 triệu',
            location: 'TP.HCM',
            time: '45',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '31',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '78',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/ngocanh.png',
            position: 'Kế toán nội bộ',
            company: 'Công ty TNHH Ngọc Anh Sài Gòn',
            salary: '14 - 20 triệu',
            location: 'TP.HCM',
            time: '45',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '31',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '78',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/ngocanh.png',
            position: 'Kế toán nội bộ',
            company: 'Công ty TNHH Ngọc Anh Sài Gòn',
            salary: '14 - 20 triệu',
            location: 'TP.HCM',
            time: '45',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '31',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '78',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/ngocanh.png',
            position: 'Kế toán nội bộ',
            company: 'Công ty TNHH Ngọc Anh Sài Gòn',
            salary: '14 - 20 triệu',
            location: 'TP.HCM',
            time: '45',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '31',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '78',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/ngocanh.png',
            position: 'Kế toán nội bộ',
            company: 'Công ty TNHH Ngọc Anh Sài Gòn',
            salary: '14 - 20 triệu',
            location: 'TP.HCM',
            time: '45',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '31',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/qn.png',
            position: 'Nhân viên kế toán kho',
            company: 'Hộ kinh doanh Quang Nguyễn',
            salary: '8 - 11 triệu',
            location: 'Cần Thơ',
            time: '78',
            requiredCV: true,
        },
        {
            logo: '/img/jobs/ngocanh.png',
            position: 'Kế toán nội bộ',
            company: 'Công ty TNHH Ngọc Anh Sài Gòn',
            salary: '14 - 20 triệu',
            location: 'TP.HCM',
            time: '45',
            requiredCV: true,
        },
    ];

    return (
        <>
            <div className={style.container}>
                <div className="h-[480px] w-full relative">
                    <Image src="/img/body/background.jpg" alt="Background Image" fill className="object-fit" priority />

                    <div className={style.overlay}>
                        <SearchBar />
                        <Carousel images={images} />
                    </div>
                </div>

                <div className={style.body}>
                    <Body title="Việc đi làm ngay" jobs={immediatelyJobs} />
                    <Body title="Việc làm gấp" jobs={urgentJobs} className="bg-[#fff3ed]" />
                    <Body title="Việc làm khác" jobs={anotherJobs} />
                </div>
            </div>
        </>
    );
}
